site_name: SmartMultiprocessing
site_url: https://smartmultiprocessing.org
site_author: Emily Hunt
site_description: >-
  A drop-in replacement for Python's `multiprocessing` library with many extra features, 
  including: memory management, smart task scheduling, a pause button, a GUI, and more.

repo_url: https://github.com/emilyhunt/smartmultiprocessing
repo_name: smartmultiprocessing

theme:
    name: material
    features:
          - navigation.sections  # Sections are included in the navigation on the left.
          - toc.integrate  # Table of contents is integrated on the left; does not appear separately on the right.
          - header.autohide  # header disappears as you scroll
    palette:
        # Light mode / dark mode
        # We deliberately don't automatically use `media` to check a user's preferences. We default to light mode as
        # (a) it looks more professional, and (b) is more obvious about the fact that it offers a (dark mode) toggle.
        - scheme: default
          primary: white
          accent: amber
          toggle:
            icon: material/weather-night
            name: Switch to dark mode
        - scheme: slate
          primary: black
          accent: amber
          toggle:
            icon: material/weather-sunny
            name: Switch to light mode
    icon:
        repo: fontawesome/brands/github  # GitHub logo in top right
        logo: "material/circle-opacity"  # Equinox logo in top left
    favicon: "_static/favicon.png"

markdown_extensions:
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - pymdownx.superfences  # Seems to enable syntax highlighting when used with the Material theme.
    - pymdownx.details  # Allowing hidden expandable regions denoted by ???
    - pymdownx.snippets:  # Include one Markdown file into another
        base_path: docs
    - admonition
    - toc:
        permalink: "¤"  # Adds a clickable permalink to each section heading
        toc_depth: 4